services:
  load-balancer:
    image: nginx:alpine
    container_name: load-balancer
    ports:
      - "8008:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
    networks:
      - lb

  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./web1/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - lb

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./web2/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - lb

networks:
  lb:
    driver: bridge
